AWSTemplateFormatVersion: 2010-09-09
Description: "Register target url for monitoring."

Parameters: 
  UrlMonLambdaLogGroup:
    Description: "Lambda Function write http status code in this log group."
    Type: String
    Default: /aws/lambda/url-monitoring
  Url:
    Description: "Target url for monitoring." 
    Type: String
  UrlAlias:
    Description: "Alias of target url for monitoring." 
    Type: String
  SnsArn:
    Description: "Arn of Amazon SNS" 
    Type: String   
  NameSpace:
    Description: "Name space for Metrics" 
    Type: String 
    Default: lambda/url-monitoring  
  Ruby:
    Description: "How to read aloud url." 
    Type: String
  AddUrlLambdaArn:
    Description: "Arn of lambda function which add url for monitoring."
    Type: String
    Default: "arn:aws:lambda:*:*:function:add-url"
  OncallStatesArn:
    Description: "Arn of state of step function."
    Type: String
    Default: "arn:aws:states:*:*:stateMachine:state-oncall"
  InvokeStepFunctionRoleArn:
    Description: "Arn of role for invoke step function."
    Type: String
  AlarmPeriod:
    Description: "The length of time to evaluate the metric or expression to create each individual data point for an alarm. It is expressed in seconds. If you choose one minute as the period, the alarm evaluates the metric once per minute."
    Type: Number
    Default: 60
  DatapointsToAlarm:
    Description: "The number of data points within the Evaluation Periods that must be breaching to cause the alarm to go to the ALARM state. The breaching data points don't have to be consecutive, they just must all be within the last number of data points equal to Evaluation Period."
    Type: Number
    Default: 3
  EvaluationPeriods:
    Description: "The number of the most recent periods, or data points, to evaluate when determining alarm state."
    Type: Number
    Default: 5
  AccountAlias:
    Description: "For identify account(environment)." 
    Type: String
  MonStates:
    Description: "Decide whether monitor url or not. 1 is True, 0 is False." 
    Type: Number
    Default: 1
    AllowedValues: [1,0]

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - 
        Label:
          default: "CloudWatch Alarm Configuration"
        Parameters:
          - AlarmPeriod
          - DatapointsToAlarm
          - EvaluationPeriods
      - 
        Label:
          default: "URL Monitoring Configuration"
        Parameters:
          - Url
          - UrlAlias
          - Ruby
      - 
        Label:
          default: "Input parameter from output of initial set up template."
        Parameters:
          - AddUrlLambdaArn
          - OncallStatesArn
          - InvokeStepFunctionRoleArn
          - UrlMonLambdaLogGroup 

Resources: 
  HttpErrorMetricFilter: 
    Type: AWS::Logs::MetricFilter
    Properties: 
      LogGroupName: 
        !Ref "UrlMonLambdaLogGroup" 
      FilterPattern: 
        !Join ['', ['[url="', !Ref Url, '", statuscode=*, exectime=*]']]
      MetricTransformations: 
        - 
          MetricValue: "$statuscode"
          MetricNamespace: !Ref "NameSpace"
          MetricName: !Join ['', [ '[', !Ref UrlAlias, ']HTTPStatusCode']]
  HttpExecTimeMetricFilter: 
    Type: AWS::Logs::MetricFilter
    Properties: 
      LogGroupName: 
        !Ref "UrlMonLambdaLogGroup" 
      FilterPattern: 
        !Join ['', ['[url="', !Ref Url, '", statuscode=*, exectime=*]']]
      MetricTransformations: 
        - 
          MetricValue: "$exectime"
          MetricNamespace: !Ref "NameSpace"
          MetricName: !Join ['', [ '[', !Ref UrlAlias, ']HTTPResponseTime']]
  HttpErrorAlarm:
    Type: "AWS::CloudWatch::Alarm"
    Properties: 
      ActionsEnabled: true
      AlarmActions: 
        - !Ref "SnsArn"
      AlarmDescription: "Monitoring HTTP status code."
      AlarmName: !Join ['', ['[', !Ref "AccountAlias", ']','[', !Ref UrlAlias, '] HTTP Error']]
      ComparisonOperator: "GreaterThanOrEqualToThreshold"
      DatapointsToAlarm: !Ref "DatapointsToAlarm"
      EvaluationPeriods: !Ref "EvaluationPeriods"
      MetricName: !Join ['', [ '[', !Ref UrlAlias, ']HTTPResponseTime']]
      Namespace: !Ref "NameSpace"
      Period: !Ref "AlarmPeriod"
      Statistic: "Maximum"
      OKActions: 
        - !Ref "SnsArn"
      TreatMissingData: "missing"
      Threshold: 400
  PutItem:
    Type: "AWS::CloudFormation::CustomResource"
    Properties:
      ServiceToken: !Ref "AddUrlLambdaArn"
      Item: 
        "urls": 
          !Ref "Url"
        "url-aliases": 
          !Ref "UrlAlias"
        "ruby": 
          !Ref "Ruby"
        "enabled": 
          !Ref "MonStates"
  HttpErrorRule:
    Type: "AWS::Events::Rule"
    Properties:
      Description: "Detect CloudWatch Alarm."
      EventPattern: 
        source:
          - "aws.cloudwatch"
        resources:
          - !GetAtt "HttpErrorAlarm.Arn"
        detail-type:
          - "CloudWatch Alarm State Change"
        detail:
          state:
            value:
              - "ALARM"
      Name: !Join ['-', ['url-monitoring', !Ref UrlAlias]]
      State: "ENABLED"
      Targets:
        -   Arn: !Ref "OncallStatesArn"
            Id: !Join ['-', ['url-monitoring', !Ref UrlAlias]]
            RoleArn: !Ref "InvokeStepFunctionRoleArn"
